version: '3.8'

services:
  web:
    build:
      context: https://github.com/MPDL/officemap.git#staging:web
      dockerfile: Dockerfile
      target: staging
    depends_on:
      api:
        condition: service_started
    ports:
      - '3003:3000'
    restart: always
  api:
    build:
      context: https://github.com/MPDL/officemap.git#staging:api
      dockerfile: Dockerfile
    environment:
      - GATEWAY_PORT=$GATEWAY_PORT
      - GATEWAY_BASE_URL=$GATEWAY_BASE_URL
      - GATEWAY_URL_PATH=$GATEWAY_URL_PATH
      - ROOMS_JSON_URL=$ROOMS_JSON_URL
      - PRINTERS_JSON_URL=$PRINTERS_JSON_URL
      - GROUNDFLOOR_IMAGE_URL=$GROUNDFLOOR_IMAGE_URL
      - EMAIL_TO=$EMAIL_TO
      - ON_EMPLOYEE_UPDATE_EMAIL_TITLE=$ON_EMPLOYEE_UPDATE_EMAIL_TITLE
      - SEND_EMAIL_ON_EMPLOYEE_UPDATE=$SEND_EMAIL_ON_EMPLOYEE_UPDATE
    ports:
      - "8787:8080"
    restart: always