version: '3.8'

services:
  officemap-sample-api:
    build:
      context: ../../
      dockerfile: docker/Dockerfile
    environment:
      - GATEWAY_PORT=$GATEWAY_PORT
      - GATEWAY_BASE_URL=$GATEWAY_BASE_URL
      - GATEWAY_URL_PATH=$GATEWAY_URL_PATH
      - ROOMS_JSON_URL=$ROOMS_JSON_URL
      - PRINTERS_JSON_URL=$PRINTERS_JSON_URL
      - GROUNDFLOOR_IMAGE_URL=$GROUNDFLOOR_IMAGE_URL
    image: officemap-sample-api
    ports:
      - '9999:8080'